-- MEMBERS
create table public.members (
  member_id bigint generated by default as identity not null,
  login_id uuid null,
  f_name character varying null,
  m_name character varying null,
  l_name character varying null,
  account_role character varying null,
  account_status character varying null,
  application_date date null,
  joined_date date null,
  membership_status character varying null,
  email character varying null,
  contact_number text null,
  birthday date null,
  deleted_at date null,
  avatar_url text null,
  civil_status text null,
  place_of_birth text null,
  spouse_name text null,
  number_of_children integer null default 0,
  office_name text null,
  title_and_position text null,
  office_address text null,
  office_contact_number text null,
  block_no text null,
  barangay character varying null,
  city_municipality character varying null,
  province character varying null,
  zip_code integer null,
  account_number text null,
  constraint members_pkey primary key (member_id),
  constraint members_account_number_key unique (account_number),
  constraint members_login_id_fkey foreign KEY (login_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger set_account_number BEFORE INSERT on members for EACH row
execute FUNCTION "generate_account_number()" ();


-- CLUB FUNDS CONTRIBUTIONS 

create table public.club_funds_contributions (
  contribution_id bigint generated by default as identity not null,
  amount bigint null,
  category character varying null,
  payment_date date null,
  payment_method character varying null,
  remarks text null,
  deleted_at date null,
  period_start date null,
  period_end date null,
  account_number text null,
  constraint club_funds_contributions_pkey primary key (contribution_id),
  constraint club_funds_contributions_account_number_fkey foreign KEY (account_number) references members (account_number) on delete CASCADE
) TABLESPACE pg_default;


-- CLUB EXPENSES 

create table public.club_funds_expenses (
  transaction_id bigint generated by default as identity not null,
  title text null,
  category text null,
  description text null,
  amount bigint null,
  transaction_date date null,
  deleted_at date null,
  constraint club_funds_transactions_pkey primary key (transaction_id)
) TABLESPACE pg_default;


-- SHARE CAPITAL

create table public.coop_cbu_contributions (
  coop_contri_id bigint generated by default as identity not null,
  source character varying null,
  amount bigint null,
  contribution_date date null,
  remarks text null,
  deleted_at date null,
  category text null,
  payment_method text null,
  account_number text null,
  constraint coop_cbu_contributions_pkey primary key (coop_contri_id),
  constraint coop_cbu_contributions_account_number_fkey foreign KEY (account_number) references members (account_number) on delete CASCADE
) TABLESPACE pg_default;


-- CLUB INCOME 

create table public.club_income (
  income_id bigint generated by default as identity not null,
  title text null,
  source text null,
  amount integer null,
  date date null,
  remarks text null,
  deleted_at date null,
  constraint club_income_pkey primary key (income_id)
) TABLESPACE pg_default;


-- INITIAL PAYMENTS

create table public.initial_payments (
  id bigint generated by default as identity not null,
  membership_fee bigint null,
  initial_share_capital bigint null,
  membership_fee_status character varying null,
  membership_payment_date date null,
  last_update date null,
  membership_remarks text null,
  membership_payment_method text null,
  share_capital_payment_method text null,
  share_capital_remarks text null,
  share_capital_payment_date date null,
  account_number text null,
  constraint initial_payments_pkey primary key (id),
  constraint initial_payments_account_number_fkey foreign KEY (account_number) references members (account_number)
) TABLESPACE pg_default;



-- LOAN PRODUCTS

create table public.loan_products (
  product_id bigint generated by default as identity not null,
  name character varying null,
  interest_rate numeric(12, 2) null,
  penalty_rate numeric(12, 2) null,
  interest_method character varying null,
  repayment_freq character varying null,
  max_term_months numeric(12, 2) null,
  min_amount numeric(12, 2) null,
  max_amount numeric(12, 2) null,
  deleted_at date null,
  constraint loan_products_pkey primary key (product_id)
) TABLESPACE pg_default;



-- LOAN APPLICATIONS 

create table public.loan_applications (
  application_id bigint generated by default as identity not null,
  account_number text null,
  amount numeric(12, 2) null,
  purpose text null,
  status character varying null,
  application_date date null,
  deleted_at date null,
  reviewed_by bigint null,
  product_id bigint null,
  updated_at date null,
  constraint loan_applications_pkey primary key (application_id),
  constraint loan_applications_account_number_fkey foreign KEY (account_number) references members (account_number) on delete CASCADE,
  constraint loan_applications_product_id_fkey foreign KEY (product_id) references loan_products (product_id),
  constraint loan_applications_reviewed_by_fkey foreign KEY (reviewed_by) references members (member_id)
) TABLESPACE pg_default;


-- LOAN ACCOUNTS 

create table public.loan_accounts (
  loan_id bigint generated by default as identity not null,
  loan_ref_number text null,
  principal numeric(12, 2) null default '0'::numeric,
  status character varying null,
  release_date date null,
  maturity_date date null,
  deleted_at date null,
  product_id bigint null,
  approved_date date null,
  account_number text null,
  approved_by bigint null,
  amount_req numeric(12, 2) null default '0'::numeric,
  total_amount_due numeric(12, 2) null default '0'::numeric,
  application_id bigint null,
  total_interest numeric(12, 2) null default '0'::numeric,
  first_due date null,
  service_fee numeric(12, 2) null default '0'::numeric,
  constraint loan_accounts_pkey primary key (loan_id),
  constraint loan_accounts_account_number_fkey foreign KEY (account_number) references members (account_number) on update CASCADE,
  constraint loan_accounts_application_id_fkey foreign KEY (application_id) references loan_applications (application_id) on delete CASCADE,
  constraint loan_accounts_approved_by_fkey foreign KEY (approved_by) references members (member_id),
  constraint loan_accounts_product_id_fkey foreign KEY (product_id) references loan_products (product_id)
) TABLESPACE pg_default;


-- PAYMENT SCHEDULES

create table public.loan_payment_schedules (
  schedule_id bigint generated by default as identity not null,
  loan_id bigint null,
  installment_no bigint null,
  due_date date null,
  principal_due numeric(12, 2) null default '0'::numeric,
  interest_due numeric(12, 2) null default '0'::numeric,
  fee_due numeric(12, 2) null default '0'::numeric,
  total_due numeric(12, 2) null default '0'::numeric,
  paid boolean null,
  paid_at date null,
  deleted_at date null,
  loan_ref_number text null,
  status character varying null default 'UNPAID'::character varying,
  amount_paid numeric(12, 2) null default '0'::numeric,
  mos_overdue smallint null default '0'::smallint,
  constraint loan_schedules_pkey primary key (schedule_id),
  constraint loan_schedules_loan_id_fkey foreign KEY (loan_id) references loan_accounts (loan_id) on delete CASCADE
) TABLESPACE pg_default;


-- PAYMENTS

create table public.loan_payments (
  payment_id bigint generated by default as identity not null,
  loan_id bigint null,
  account_number text null,
  total_amount numeric(12, 2) null,
  payment_method character varying null,
  payment_date date null,
  receipt_no text null,
  deleted_at date null,
  loan_ref_number text null,
  principal numeric(12, 2) null,
  fees numeric(12, 2) null,
  interest numeric(12, 2) null,
  status character varying null default 'Paid'::character varying,
  schedule_id bigint null,
  constraint loan_payments_pkey primary key (payment_id),
  constraint loan_payments_loan_id_fkey foreign KEY (loan_id) references loan_accounts (loan_id) on delete CASCADE,
  constraint loan_payments_schedule_id_fkey foreign KEY (schedule_id) references loan_payment_schedules (schedule_id)
) TABLESPACE pg_default;


-- SETTINGS 

create table public.settings (
  id bigint generated by default as identity not null,
  loan_service_fee numeric null default '0'::numeric,
  theme text null default 'light'::text,
  penalty_rate numeric null default '0'::numeric,
  constraint settings_pkey primary key (id)
) TABLESPACE pg_default;